#!/bin/bash

echo "🚀 Invoice Calculator - Quick Deploy"
echo "===================================="
echo ""
echo "Your application is ready! Here are your deployment options:"
echo ""
echo "📦 Option 1: Netlify Drop (Fastest - 30 seconds)"
echo "   1. Visit: https://app.netlify.com/drop"
echo "   2. Drag this entire folder onto the page"
echo "   3. Done! Get your live URL"
echo ""
echo "📦 Option 2: Netlify Git (Automatic updates)"
echo "   1. Visit: https://app.netlify.com"
echo "   2. Click 'Add new site' → 'Import an existing project'"
echo "   3. Choose GitHub → Select: mertoksuz/invoice_calculator"
echo "   4. Click 'Deploy' (no configuration needed!)"
echo "   5. Your site deploys automatically on every git push"
echo ""
echo "📦 Option 3: Vercel (Alternative)"
echo "   1. Visit: https://vercel.com/new"
echo "   2. Import your GitHub repo: mertoksuz/invoice_calculator"
echo "   3. Click 'Deploy'"
echo ""
echo "🎯 What you'll get:"
echo "   ✅ Free HTTPS domain (yourname.netlify.app or .vercel.app)"
echo "   ✅ Global CDN"
echo "   ✅ Automatic SSL certificate"
echo "   ✅ Can add custom domain for free"
echo ""
echo "📊 Your GitHub repo: https://github.com/mertoksuz/invoice_calculator"
echo ""
echo "Would you like me to open the Netlify deployment page? (y/n)"
read -r response

if [[ "$response" =~ ^[Yy]$ ]]; then
    echo "Opening Netlify..."
    open "https://app.netlify.com/start/deploy?repository=https://github.com/mertoksuz/invoice_calculator"
else
    echo ""
    echo "No problem! When you're ready, visit one of the URLs above."
fi

echo ""
echo "✨ Your app is production-ready with all features:"
echo "   📤 Upload invoices (PDF, Excel, CSV, Images)"
echo "   💰 Add multiple additional costs"
echo "   🧮 Calculate with custom profit margins"
echo "   🌍 Support for 12+ currencies"
echo "   📊 Export to Excel/CSV"
echo "   📱 Mobile responsive"
echo ""
echo "🎉 Happy deploying!"
